### ISSUE TITLE
DWT: Enviament metadades de document escanejat

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/pluginsib-scanweb#15]
Es proposa que el Dynamic Web Twain faci l'enviament de la informació de les metadades a l'aplicació 'host'.

Ho pot fer mitjançant el mètode de DWT "SetHttpFormField" [https://developer.dynamsoft.com/dwt/api-reference/uploading-downloading/http-download-upload/sethttpformfield](url)

**Comment by anadal-fundaciobit** [comment]
Adjunt algunes captures de les noves metadades i del nou aspecte del plugin:

![imatge](https://user-images.githubusercontent.com/17084256/78358044-cfd9b000-75b2-11ea-8324-881cb17eb3ad.png)

![imatge](https://user-images.githubusercontent.com/17084256/78358075-db2cdb80-75b2-11ea-926d-59ebe265648c.png)


Les noves metadades es descriuen en aquesta ISSUE: https://github.com/GovernIB/pluginsib-scanweb/issues/16

S'han afegir dues noves propietats: 
*[BASE].plugins.scanweb.dynamicwebtwain.hidetipusdocumental: serveix per amagar la seleccio del tipus documental
*[BASE].plugins.scanweb.dynamicwebtwain.hideidioma: serveix per amagar la selecció de l'idioma del document.
