### ISSUE TITLE
API ScanWebConfig: Afegir metadades

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/pluginsib-scanweb#16]
Es proposa la recolecció de les metadades que necessita tot document electrònic (annex I [d'aquesta Resolució](https://www.boe.es/boe/dias/2011/07/30/pdfs/BOE-A-2011-13169.pdf) i de les metadades de la NTI de digitalització de documents que indica la [Guia de aplicació de digitalizació de documents ](https://www.hacienda.gob.es/Documentacion/Publico/SGT/CATALOGO_SEFP/284_11.Guia%20de%20aplicacion%20de%20digitalizacion%20(acc).pdf) en la pàgina 17, punt 40.

Fer-ho dins la llista de Metadades de ScanWebConfig: List<Metadada> metadades

**Comment by anadal-fundaciobit** [comment]
Les noves metadades especifiques d'escaneig i digitalització s'han afegit a una classe ja existent de PluginIB-Core anomenada MetadataConstants.java: El canvis són:

*  ENI_TIPO_DOCUMENTAL: Afegit els valors des de TD51 fins TD69

Les noves metadades són:
(a) INVENTADES:
  (a.1) PAPER_SIZE: Conté un String amb el nom del tipus de paper (A4, Letter, ...) L'eEMGDE  defineix la metadada eEMGDE.CaracteristicasTecnicas.Tamano.DimensionesFisicas però aquesta té alguns inconvenients: es comenta en la descripció que "No debe utilizarse en sistemas que sólo gestionen documentos digitales" (no se la raó ...), a més s'hauria de definir les dimensions de cada tipus de paper i per finalitzar necessitarien definir una segona metadada eEMGDE.CaracteristicasTecnicas.Tamano.Unidades per establir les unitats (mm, cm, polsades, ...)
  (a.2) OCR: Boolea que indica si el document escanejat  ha passat per un procés d'OCR
  (a.3) FUNCTIONARY_USERNAME, FUNCTIONARY_FULLNAME i FUNCTIONARY_ADMINISTRATIONID: informació del funcionari que realitza l'escaneig. Serà d'utilitat en el plugin de scanweb de DigitalIB.

(b) Recollides de eEMGDE
   (b.1) RESOLUTION: eEMGDE.CaracteristicasTecnicas.Resolucion
   (b.2)  PROFUNDIDAD_COLOR: eEMGDE.CaracteristicasTecnicas.ProfundidadColor
