### ISSUE TITLE
Plugin DigitalIB: Llegir i transformar metadades

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/pluginsib-scanweb#17]
Modificar la implementació del Plugin de DigitalIB, per llegir de l'API ScanWeb Simple els camps requerits i transformar-ho a les metadades descrites. Actualment ja es fa amb els camps functionary.username, functionary.fullname, functionary.administrationid i document.language.

S'hauran de llegir certes dades addicionals del camp  "List<Metadata> metadades" de ScanWebConfig.

**Comment by anadal-fundaciobit** [comment]
Dades d'un escaneig simple:

![imatge](https://user-images.githubusercontent.com/17084256/79451928-9dcf4180-7fe7-11ea-9e77-94ba18fdf783.png)

**Comment by anadal-fundaciobit** [comment]
Dades d'un escaneig amb firma: 

![imatge](https://user-images.githubusercontent.com/17084256/79451966-ade72100-7fe7-11ea-9eea-689daf3051aa.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat
